#!/bin/bash
#
# slackbuild script for pwlib
# by rafael at riseup.net
#

if [ -s "slack-required" ]; then
  echo Recomended and required packages for building pwlib are:
  cat slack-required | sed -e 's/^/\t/'
  if [ "$INTERACT" != "no" ]; then
    echo If you dont have those installed, press Ctrl-C. Otherwise, hit ENTER.
    read crap
#  else
#    echo Sleeping 3 seconds...
#    sleep 3
  fi
fi

CWD="`pwd`"

if [ -f ~/.slackbuildrc ]; then
  source ~/.slackbuildrc
elif [ -f /etc/slackbuildrc ]; then
  source /etc/slackbuildrc
fi

# default settings
PACKAGE="pwlib"
ARCH=${ARCH:=i486}
VERSION=${VERSION:=1.10.2}
BUILD=${BUILD:=1rd}
SRC_DIR=${SRC:=$CWD}
TMP=${TMP:=/tmp}
REPOS=${REPOS:=$TMP}

if [ "$ARCH" == "x86_64" ]; then
  LIBDIR=/usr/lib64
else
  LIBDIR=/usr/lib
fi

RTOOL="wget"
PACKAGE_EXT="gz"
SRC="$PACKAGE-$VERSION.tar.$PACKAGE_EXT"
URL="http://www.ekiga.org/admin/downloads/latest/sources/sources/$SRC"

SRC_DIR="$SRC_DIR/$PACKAGE"
mkdir -p $SRC_DIR

if [ "$PACKAGE_EXT" == "bz2" ]; then
  tarflag="j"
else
  tarflag="z"
fi

if [ "$RTOOL" == "wget" ] && [ ! -f "$SRC_DIR/$SRC" ]; then
  wget "$URL" -O "$SRC_DIR/$SRC"
fi

TMP="$TMP/$PACKAGE"
rm -rf $TMP
mkdir -p $TMP
cd $TMP

tar xvf$tarflag $SRC_DIR/$SRC
cd $PACKAGE-$VERSION

if [ -f "$CWD/$PACKAGE-$VERSION.diff" ]; then
  patch -p1 < $CWD/$PACKAGE-$VERSION.diff
fi

./configure --prefix=/usr --sysconfdir=/etc --libdir=$LIBDIR --enable-plugins
make || exit 32
make DESTDIR=$TMP/package-$PACKAGE install

CWD="`pwd`"

cd $TMP/package-$PACKAGE

find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

mkdir install
cat << EOF > install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

     |-----handy-ruler-----------------------------------------------------|
pwlib: pwlib (PWLib is a library to allow portable applications)
pwlib:
pwlib: PWLib is a moderately large class library that has its genesis many years
pwlib: ago as a method to product applications to run on both Microsoft Windows 
pwlib: and Unix X-Windows systems. It also was to have a Macintosh port as well 
pwlib: but this never eventuated. The parts of the library relating to GUI 
pwlib: functions have also been removed.
pwlib: 
pwlib: 
pwlib: 
pwlib: 
EOF

# docs
mkdir -p usr/doc/$PACKAGE-$VERSION

for file in ReadMe.txt ReadMe_QOS.txt History.txt ;do
  cp $CWD/$file* usr/doc/$PACKAGE-$VERSION/
done

makepkg -c y -l y $REPOS/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz

if [ "$CLEANUP" == "yes" ]; then
  rm -rf $TMP
fi

