#!/bin/bash
#
# slackbuild for rssh
# requires: kernel-source-2.6, kernel-headers-2.6
#

CWD=`pwd`

if [ -f ~/.slackbuildrc ]; then
  source ~/.slackbuildrc
elif [ -f /etc/slackbuildrc ]; then
  source /etc/slackbuildrc
fi

# default settings
PRGNAM="lm_sensors"
PACKAGE="$PRGNAM"
ARCH=${ARCH:=i486}
VERSION=${VERSION:=2.9.1}
BUILD=${BUILD:=3rha}
SRC_DIR=${SRC:=$CWD}
TMP=${TMP:=/tmp}
REPOS=${REPOS:=$TMP}

PACKAGE_EXT="gz"
SRC="$PACKAGE-$VERSION.tar.$PACKAGE_EXT"
URL="http://dl.lm-sensors.org/lm-sensors/releases/$SRC"

RTOOL="wget"

gpg --import << EOPGP
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PGPfreeware 5.0i for non-commercial use

mQCNAzaeL3sAAAEEAL7roqireHxJ43Xo1oOWAUbba5DVfQX8Cnv99I1VQ1suFxVn
HWpWjlI0BUaMZzP9JF9F/xZhpd9dyjj3giuFReyj8Qk5e6Q0eSWSL+0CADi9Pesm
zQQt4GmPpDfLKbzFUWCUNbB5vAC8p9Fj2frHBqcF7z3AR3u+3h8uYrXvyThJAAUR
tCVQaGlsaXAgRWRlbGJyb2NrIDxwaGlsQG5ldHJvZWRnZS5jb20+iQCVAwUQNp4v
ex8uYrXvyThJAQEJFwP+IED7wi0Spa1KpVp9ywK9r7Fu7WLUhv0stD2GlFL+USa7
UTB0XuFXuOFVVNtBauj5a1morjVGIcwYkJ4prTLYe+ok+AjfeCjodPxzrSqPgf3n
xbQqRg0vMCxIHHBP8dv2guEBii06GhvculveSvvyOZGEKLAV6btKXvIxJI7yRHU=
=Mzd5
-----END PGP PUBLIC KEY BLOCK-----

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PGPfreeware 5.0i for non-commercial use

mQGiBDfK4agRBADvyYYefBEaVxx7plH0qJayzZIEjJOjBwsDZl5HWfx+XbZrtGzg
ouhbw+a9vcA5birNt7GhlMHiKYQ20fTircGfJr1WgIDRQp2/LgFRBaL9sbYIpgBv
EM6+4y7vsSamkVl+xanhGDkLHn95zD+fSjTY4BbgsL7nqyVe6m96IZ1a2wCg/y61
6iVL3rqRSzu4zeNoB4XPjJ8D/2ZMoKVvlKrW9zmfC/Ymty10BxPKmtXg2+UoWhLc
BO0Cn22iktmCHQIgn/tj0GqB+zxy87vOANlge2TXCgxbfp1mDFBPHZ3R5kLh4AU3
qMG0eOIYl7Jng848WmMWeFCyw1rw8i3OdlOel+vtKJvw6IhJsThqL6UKjVVUSTcR
9TQfA/4uqG3rf+8xF6dFsoTCyk+Vk703Uli0MJmN36fuLw147LfZaC858V2fDCAF
PamhhFe5Tf90Ini/pSby6SCPd06iMLN8HdbfrAwPGGJYDrST1epnNr/7seYioFOe
mr7CUKqbQCR7um7VQbzIQ8PG5tsiphmebyKQ5YQlF24wfQMmyrQHcGhpbGRzc4kA
SwQQEQIACwUCN8rhqAQLAwECAAoJEOCiVzdlI2rVUdUAn0B81EIPhtLH6lM5kKf/
LyEupz9gAJ44uLsibf2unlk8sE1Znox4BeDHZLQZcGhpbEBzdGltcHkubmV0cm9l
ZGdlLmNvbYkASwQQEQIACwUCN8rniwQLAwECAAoJEOCiVzdlI2rVj7sAoJyc5Yd4
qTx8J+Uqx3blYGgbYCMGAKC41VDaAktzuW7x6/fisE1bOgangbkCDQQ3yuGoEAgA
9kJXtwh/CBdyorrWqULzBej5UxE5T7bxbrlLOCDaAadWoxTpj0BV89AHxstDqZSt
90xkhkn4DIO9ZekX1KHTUPj1WV/cdlJPPT2N286Z4VeSWc39uK50T8X8dryDxUcw
Yc58yWb/Ffm7/ZFexwGq01uejaClcjrUGvC/RgBYK+X0iP1YTknbzSC0neSRBzZr
M2w4DUUdD3yIsxx8Wy2O9vPJI8BD8KVbGI2Ou1WMuF040zT9fBdXQ6MdGGzeMyEs
tSr/POGxKUAYEY18hKcKctaGxAMZyAcpesqVDNmWn6vQClCbAkbTCD1mpF1Bn5x8
vYlLIhkmuquiXsNV6TILOwACAgf/YDv43LHUBX4wGkVbLJ2DU8tOAp5Od0pxXaUF
FMGzTuR3W5IdS9YjTo9NdE6DlsX34yU1iLTyjnqApDfu2Uz2oeM1RULYmK9srA2M
LZoDAiVtwsqRX5x0QlkdrDn6ngZMnfe9n8d3fxxqC6wtI+EpXUEk+G4hafowyM2j
ogibnD8TGwjCFD5OQSG50yRCEykZez3thX2jRrlZLRhhtU1eb2GbJ7NMoFoAH079
me+8kspMvYaPAQg/vpml89BNWmdu3OdtR7qFO9vNbDRFJMZLIucC6sWWMPSXltcI
rOHdFtnux8OxY+57juMgkOR5JsyY1WizxmWgIAptLv7KlLYkiokAPwMFGDfK4ajg
olc3ZSNq1REC58kAoLyb4jp4/9/QUEQrFFmyy4M/65xuAKCnpPd37PhwQn0kLIlo
BP7wPk2BgQ==
=l+kY
-----END PGP PUBLIC KEY BLOCK-----
EOPGP

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

if [ "$PACKAGE_EXT" == "bz2" ]; then
  tarflag="j"
else
  tarflag="z"
fi

SRC_DIR="$SRC_DIR/$PACKAGE"
mkdir -p $SRC_DIR

if [ "$RTOOL" == "wget" ] && [ ! -f "$SRC_DIR/$SRC" ]; then
 wget "$URL" -O "$SRC_DIR/$SRC"
 wget "$URL.asc" -O "$SRC_DIR/$SRC.asc"
fi

gpg --verify $SRC_DIR/$SRC.asc $SRC_DIR/$SRC || echo WARNING: Could not check signature or WRONG signature found.

TMP="$TMP/$PACKAGE"
rm -rf $TMP
mkdir -p $TMP
cd $TMP

rm -rf $PACKAGE-$VERSION $PACKAGE-$VERSION-$ARCH-$BUILD.tgz

tar xvf$tarflag $SRC_DIR/$PACKAGE-$VERSION.tar.$PACKAGE_EXT
cd $PACKAGE-$VERSION

sed -e 's/^I2C_HEADERS := \/usr\/local\/include/I2C_HEADERS := \/usr\/include/' \
    -e 's/^PREFIX := \/usr\/local/PREFIX := \/usr/' Makefile > Makefile.new

if [ "$ARCH" == "x86_64" ]; then
  sed -e 's/LIBDIR := $(PREFIX)\/lib/LIBDIR := $(PREFIX)\/lib64/' Makefile.new > Makefile
else
  mv Makefile.new Makefile
fi

make user
make DESTDIR=$TMP/package-$PACKAGE user_install

CWD="`pwd`"

mkdir -p $TMP/package-$PACKAGE/install
cd $TMP/package-$PACKAGE

find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

cat << EOF > install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

          |-----handy-ruler-----------------------------------------------------|
lm_sensors: lm_sensors (Linux sensors drivers and hardware monitoring tools)
lm_sensors:
lm_sensors: lm_sensors provides essential drivers for monitoring the
lm_sensors: temperatures, voltages, and fans of Linux systems with hardware
lm_sensors: monitoring devices. It contains Linux 2.4 drivers for sensor chips
lm_sensors: and I2C and SMBus masters, text-based tools for sensor reporting,
lm_sensors: and a library for sensors access called "libsensors". It also
lm_sensors: contains tools for sensor hardware identification and I2C bus probing.
lm_sensors:
lm_sensors:
lm_sensors:
EOF

# config
mv etc/sensors.conf etc/sensors.conf.new

# docs
mkdir -p usr/doc/$PACKAGE-$VERSION
cp $CWD/{BACKGROUND,BUGS,CHANGES,CONTRIBUTORS,COPYING,INSTALL,QUICKSTART,README,README.thinkpad,TODO} usr/doc/$PACKAGE-$VERSION/

makepkg -c y -l y $REPOS/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz

if [ "$CLEANUP" == "yes" ]; then
  rm -rf $TMP
fi

