#!/bin/bash
#
#  boost.SlackBuild is free software; you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation; either version 2 of the License, or any later version.
#
#  boost.SlackBuild is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
#  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with
#  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
#  Place - Suite 330, Boston, MA 02111-1307, USA
#
# slackbuild script for boost
# by rafael at riseup.net
#

if [ -s "slack-required" ]; then
  echo Recomended and required packages for building boost are:
  cat slack-required | sed -e 's/^/\t/'
  if [ "$INTERACT" != "no" ]; then
    echo If you dont have those installed, press Ctrl-C. Otherwise, hit ENTER.
    read crap
  else
    echo Sleeping 3 seconds...
    sleep 3
  fi
fi

CWD="`pwd`"

if [ -f "/etc/slackbuildrc" ]; then
  source /etc/slackbuildrc
fi

if [ -f "~/.slackbuildrc" ]; then
  source ~/.slackbuildrc
fi

# default settings
PACKAGE="boost"
ARCH=${ARCH:=i486}
VERSION=${VERSION:=1.35.0}
BUILD=${BUILD:=1rd}
SRC_DIR=${SRC:=$CWD}
TMP=${TMP:=/tmp}
REPOS=${REPOS:=$TMP}

rm -rf $TMP/$PACKAGE
mkdir -p $SRC_DIR/$PACKAGE $TMP/$PACKAGE

export PACKAGE VERSION ARCH BUILD SRC_DIR TMP REPOS

if which simpletrack &> /dev/null; then
  simpletrack $PACKAGE.build
else
  slacktrack -b $REPOS -x $TMP,$SRC_DIR,/dev -jefkzp "$PACKAGE-$VERSION-$ARCH-$BUILD.tgz" "./$PACKAGE.build"
fi

# doinst fix
if [ -f "$CWD/$PACKAGE-$VERSION-doinst.diff" ]; then
  rm -rf $TMP/package-$PACKAGE
  mkdir $TMP/package-$PACKAGE
  cd $TMP/package-$PACKAGE
  explodepkg $TMP/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz
  patch -p0 < $CWD/$PACKAGE-$VERSION-doinst.diff
  makepkg -c y -l y $REPOS/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz
fi

if [ "$CLEANUP" == "yes" ]; then
  rm -rf $TMP/$PACKAGE
fi

