#!/bin/bash
#
# SlackBuild script to call mod_python.build with correct settings
#

CWD="`pwd`"

if [ -f ~/.slackbuildrc ]; then
  source ~/.slackbuildrc
elif [ -f /etc/slackbuildrc ]; then
  source /etc/slackbuildrc
fi

# default settings
PACKAGE="mod_python"
VERSION=${VERSION:=2.7.11}
ARCH="${ARCH:=x86_64}"
BUILD=${BUILD:=3rha}
SRC_DIR=${SRC:=$CWD}
TMP=${TMP:=/tmp}
REPOS=${REPOS:=$TMP}

rm -rf $TMP/$PACKAGE
mkdir -p $SRC_DIR/$PACKAGE $TMP/$PACKAGE

slacktrack -b $REPOS -x $TMP,$SRC_DIR,/dev -jefkzp "$PACKAGE-$VERSION-$ARCH-$BUILD.tgz" "./$PACKAGE.build"

if [ "$CLEANUP" == "yes" ]; then
  rm -rf $TMP/$PACKAGE
fi
