#!/bin/bash
#
#  rkhunter.SlackBuild is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or any later version.
#
#  rkhunter.SlackBuild is distributed in the hope that it
#  will be useful, but WITHOUT ANY WARRANTY; without even the
#  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
#  PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public
#  License along with this program; if not, write to the Free
#  Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
#  MA 02111-1307, USA
#
# SlackBuild for Rootkit Hunter
# http://rkhunter.sourceforge.net/
#
# Author: Luis ( luis at riseup d0t net )
#

# Look for slackbuildrc
if [ -f ~/.slackbuildrc ]; then
  source ~/.slackbuildrc
elif [ -f /etc/slackbuildrc ]; then
  source /etc/slackbuildrc
fi

# Set variables
CWD="$(pwd)"
SRC_NAME="rkhunter"
PKG_NAME="rkhunter"
ARCH="noarch"
SRC_VERSION=${VERSION:=1.3.4}
PKG_VERSION="$(echo "$SRC_VERSION" | tr '[[:blank:]-]' '_')"
BUILD=${BUILD:=1ls}
SRC_DIR=${SRC_DIR:=$CWD}/$PKG_NAME
TMP=${TMP:=/tmp}
PKG=${PKG:=$TMP/package-$PKG_NAME}
REPOS=${REPOS:=$TMP}
PREFIX=${PREFIX:=}
PKG_WORK="$TMP/$SRC_NAME"
CONF_OPTIONS=${CONF_OPTIONS:=}
NUMJOBS=${NUMJOBS:=}

# Set system libraries' path based on $ARCH
if [ "$ARCH" = "x86_64" ]; then
  LIBDIR="$PREFIX/lib64"
else
  LIBDIR="$PREFIX/lib"
fi

# Set error codes (used by createpkg)
ERROR_WGET=31;      ERROR_MAKE=32;      ERROR_INSTALL=33
ERROR_MD5=34;       ERROR_CONF=35;      ERROR_HELP=36
ERROR_TAR=37;       ERROR_MKPKG=38;     ERROR_GPG=39
ERROR_PATCH=40;     ERROR_VCS=41;       ERROR_MKDIR=42

# Clean up any leftovers of previous builds
rm -rf "$PKG_WORK" 2> /dev/null
rm -rf "$PKG" 2> /dev/null

# Create directories if necessary
mkdir -p "$SRC_DIR" || exit $ERROR_MKDIR
mkdir -p "$PKG" || exit $ERROR_MKDIR
mkdir -p "$REPOS" || exit $ERROR_MKDIR
mkdir -p "$PKG_WORK" || exit $ERROR_MKDIR

# Dowload source if necessary
SRC="$SRC_NAME-$SRC_VERSION.tar.gz"
URL="http://downloads.sourceforge.net/rkhunter/$SRC"

if [ ! -s "$SRC_DIR/$SRC" ] || ! gzip -t "$SRC_DIR/$SRC" 2> /dev/null; then
  wget "$URL" -O "$SRC_DIR/$SRC" || exit $ERROR_WGET
fi

# Import minimized signing key from
# http://keyserver.noreply.org/pks/lookup?op=get&search=0xEA5F4CD3A65F5E17
gpg --import << EOKEY || exit $ERROR_GPG
-----BEGIN PGP PUBLIC KEY BLOCK-----

mIsERqMwPQEEAI0vYVqBSHTexjttt9iFOItnJy56vIKnBNaG/PqPMvTY3HHzWfRN
p62YPB+F+htLzfKwUSDVaC0BYP8zl09lzNcTeb5JkUcT/qaSEssdBQFLI2H/7A2y
2HXzkntijiWTLw7YzWk45d8YzJ8SMJMu1CFX26VqgDZJ27hdDEJ7+t97AAQLiLcE
HwECACECBwEXDIARimBlb8JjS5zaoqc8egL55ydMtikFAkajMD0ACgkQ6l9M06Zf
XheZPgP/TSaw8hyFQ14gD6fJztiXkX8lyTiNsUe6gk8fJKPYVGBq3A+iXRSBO82L
jFetGczv6qtif6TgqDwHjhFZpHBJFsj1RwYyxbun0nCnOVOcPhi3vZTTci6lH0D3
My8Cgivao+uhKedngpdIQ7wUe6wqiWkFzr5KvD5qQ0pThWp2oP60LyJya2h1bnRl
ckBodXNobWFpbC5jb20iIDxya2h1bnRlckBodXNobWFpbC5jb20+iKoEEAECABQG
FQgJCgMCBgsJCAcKBAUCRqMwPQAKCRDqX0zTpl9eF1zlA/97CoZ6m6cFMB3srfk6
kZ1vBEFaEYvuGTcSTQCLSsc4IlUUeBfqKHMqpyk8tOcGJ79BR3tehXreOvAhuuBc
ANySDexMqcyDEWjC0SCsmAZi1lM9pARbluRatnBLGX+WBizrXKNKwMHyUE43a0zz
87CQlC2/hZ8VD3FeqzSxEfwNA7kBCwRGozA9AQgAm9rKCo7dnephV75p9/Zl30Gb
uvYmGNwgiPPu6XnczJAXd3GQ+uHvQjHdrO6l2tm+KufmYxragLll0OvMjDlzjfO1
FXghrecUbuF2sOQyZihRvGctTSouEZ6n+Rp0+90uURXIq9Icot6flZ1c8TqItpNR
CP8+4AuEn8uXqEnKToqiEFX5jRlOSZ0Gn6v+MjgMRDwcZzQne0u7NYl9lxA29X+b
lTLIM5+YP2txeSjCGFW0x5fl6lLcJ+ySEnN5B/AmcWvl3xarvprQUvd1AsWosEhm
V5yFIOx9O7UWd2PEwMDKZH1owEw9E/8JHc8ojss3+XXzbZBB/WkE2d78kqKUwQAE
C4icBBgBAgAGBQJGozBAAAoJEOpfTNOmX14XN8QEAIkvNyAxQAVgTkVHxepFLbN+
/Xdc9pMkP1yzau63RGCwbvC1R2RcnnaTAz/YyYWQkFqErmOsmg+dnZTXEcnUuBL7
F4e0cLF56zfSUmsxTa4Jyotm2bsxGn80JW0F4LbrXlcRDfAXefLMlICiKICzTxHM
rNQCISFRMlsqLJJ2nfFJiQG7BBgBAgAGBQJIMihyASnAXSAEGQECAAYFAkgyKGQA
CgkQwrCJgiZEdQXAigf/SlJJ1exnJ1Hnz8aO+xhhAbblJTVUnsBxKgBS15hLF/G7
7Gz3JVr6a4JLRoTWccwAjVHjcjFC2IVp0HkM+uEFlAFJeVRV0qQ1nFnpSVkfhPBl
q79YhqO5Zpxg3qM/+sWNaGUYncPWjCiex3tusLcLZt2JWOkfmULR+JhpZExsbFTE
LIXi1pupQAOxVgxA6pdLIyxirr+m2vafYTbk3DN4TsYwFtkXV1kMuqNKt3FyYqC7
l5s99pcJEhxehxAavRXnOcWU3SX+qXMs2SbxL81PrcBOrTGQNko77ZN6mjMOC0/d
TwUQpQFiD21NDhNbdyjk/XlQOftYnGOIkHCes9MMLAkQ6l9M06ZfXhe8VAP+KC6r
sieh5XRUCx5zX0JnU02WkXh18XPbQChwwSKhFbSbGHQvEID+4cLizPasROY6wVNZ
Mg793mq9RiSUZmPncpBDT3JIbKhpgPDbAo34gXzODJaWlCpfEIg8KhclQfPrH4uS
4h5hiB/STD6ha+KoTbV+9aBjmQBos8mB3r4pZ1E=
=o6DW
-----END PGP PUBLIC KEY BLOCK-----
EOKEY

# Dowload source's signature if necessary and check it
if [ ! -s "$SRC_DIR/$SRC.asc" ]; then
  wget "$URL.asc" -O "$SRC_DIR/$SRC.asc" || exit $ERROR_WGET
fi

gpg --verify "$SRC_DIR/$SRC.asc" "$SRC_DIR/$SRC" || exit $ERROR_GPG


# Untar
cd "$PKG_WORK"
tar --no-same-owner --no-same-permissions -xvf "$SRC_DIR/$SRC" || exit $ERROR_TAR
PKG_SRC=`ls -l | awk '/^d/ { print $8 }'`
cd "$PKG_SRC"

# Install
if [ -z "$PREFIX" ]; then
  RPM_BUILD_ROOT="$PKG" \
    ./installer.sh --layout RPM --striproot "$PKG" --install || exit $ERROR_INSTALL
  mv -f "$PKG"/etc/rkhunter.conf "$PKG"/etc/rkhunter.conf.new
  mv -f "$PKG"/usr/local/share/* "$PKG"/usr
  rm -rf "$PKG"/usr/local/share
else
  mkdir -p "$PKG/$PREFIX" || exit $ERROR_MKDIR
  ./installer.sh --layout custom "$PKG/$PREFIX" --striproot "$PKG" --install || exit $ERROR_INSTALL
  mv -f "$PKG/$PREFIX"/etc/rkhunter.conf "$PKG/$PREFIX"/etc/rkhunter.conf.new
  mv -f "$PKG/$PREFIX"/share/* "$PKG"/usr
  rm -rf "$PKG/$PREFIX"/share
  if ! echo "$PATH" | grep -q "$PREFIX"/bin; then
    mkdir -p "$PKG"/usr/local/bin || exit $ERROR_MKDIR
    ln -sf "$PREFIX"/bin/rkhunter "$PKG"/usr/local/bin/rkhunter
  fi
fi

# Compress and link manpages
if [ -d "$PKG"/usr/man ]; then
  ( cd "$PKG"/usr/man
    for manpagedir in $(find . -type d -name "man*") ; do
      ( cd $manpagedir
        for eachpage in $( find . -type l -maxdepth 1) ; do
          ln -s $( readlink $eachpage ).gz $eachpage.gz
          rm $eachpage
        done
        gzip -9 *.?
      )
    done
  )
fi

# Add package description (slack-desc)
mkdir -p "$PKG/install" || exit $ERROR_MKDIR
cat << EODESC > "$PKG/install/slack-desc"
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.

        |-----handy-ruler------------------------------------------------------|
rkhunter: Rootkit Hunter
rkhunter: 
rkhunter: Rootkit Hunter (RKH) is a security monitoring and analyzing tool for
rkhunter: POSIX compliant systems. It checks your computer for the presence of
rkhunter: rootkits and other unwanted tools.
rkhunter: 
rkhunter: For more information, http://rkhunter.sourceforge.net/
rkhunter: 
rkhunter: 
rkhunter: 
rkhunter: 
EODESC

# Add a post-installation script (doinst.sh)
cat << EOSCRIPT > "$PKG/install/doinst.sh"
config() {
  NEW="\$1"
  OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
  # If there's no config file by that name, mv it over:
  if [ ! -r \$OLD ]; then
    mv \$NEW \$OLD
  elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then
    # toss the redundant copy
    rm \$NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}

config $PREFIX/etc/rkhunter.conf.new
EOSCRIPT

# Build the package
cd "$PKG"
makepkg -l y -c n "$REPOS/$PKG_NAME-$PKG_VERSION-$ARCH-$BUILD.tgz" || exit $ERROR_MKPKG

# Delete source and build directories if requested
if [ "$CLEANUP" == "yes" ]; then
  rm -rf "$PKG_WORK" "$PKG"
fi
